# Generated by Django 4.1.5 on 2023-01-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Pyhsics', 'Pyhsics'), ('Algebra', 'Algebra'), ('English', 'English')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Pyhsics', 'Pyhsics'), ('Algebra', 'Algebra'), ('English', 'English')], max_length=20, null=True),
        ),
    ]
